### ISSUE TITLE
[junit5] org.osgi.test.junit.bundle is not exported

### ISSUE THREAD

**Issue by kriegfrj** [osgi/osgi-test#351]
This was a bit of an oversight on our part. We have useful utilities in here that can't be used because we didn't actually export the package.

This went undetected because our test bundle is implemented as a fragment and had special access rights to that package which our client bundles will not have. One of the reasons to prefer implementing tests in standalone bundles rather than as fragments.

**Comment by bjhargrave** [comment]
I have started the 1.0.1 stream on the release branch and cherry-picked the fix onto the branch.

**Comment by kriegfrj** [comment]
Technically,  shouldn't it be 1.1? We're adding to the public API? I suppose it is not so critical with the bundle version as long as it's increasing and the package versioning is correct?

**Comment by bjhargrave** [comment]
> Technically, shouldn't it be 1.1? We're adding to the public API?

Attempting to use semantic versioning for bundle versions leads to madness. Bundles are aggregates of package which can change from time to time. Packages can be added or removed because they are now in some other bundle. Just because a package is added or removed does not really affect a user because they smartly import packages and get them from which ever bundle exports them. Users of Require-Bundle can be affected but they really should be using package imports. :-)

So for bundle versions, we are communicating to humans using the bundles. Resolvers care about the packages and their versions. And in this case, 1.0.1 makes sense since we are bug fixing the 1.0.0 where we forgot to export the package and our tests failed to detect this error.

**Comment by tjwatson** [comment]
If we don't want the bundles produced by the OSGi spec build to be treated as if the osgi.wiring.bundle is an API contract with proper semantic versioning then perhaps we should consider adding some mandatory matching attribute to their Bundle-SymbolicName header:

```
Bundle-SymbolicName: org.osgi.service.component; mandatory:=doNotRequire; doNotRequire=Bundle
```
This would force anyone trying to do require bundle on our bundles to do this:

```
Require-Bundle: org.osgi.service.component; doNotRequire=Bundle
```

**Comment by bjhargrave** [comment]
I don't think we need to go that far. People who chose to use Require-Bundle do so at their own peril. If they use Bnd to make their bundles, the bundles will always use Import-Package.



> OSGi spec build

Also, this repo is in the OSGi Technology Project. :-)
