### ISSUE TITLE
deduplicate the test code between junit4 and junit5 test harnesses

### ISSUE THREAD

**Issue by rotty3000** [osgi/osgi-test#36]
> If `ServiceUseRule` and `ServiceUseExtension` had a common base class, then their respective test classes could too. That way you can avoid duplicating the test code between each and also give a greater guarantee that their behaviour is consistent.

_Originally posted by @kriegfrj in https://github.com/osgi/osgi-test/pull/34_

**Comment by kriegfrj** [comment]
This is not as clean as I had thought when I first made the suggestion, because as @rotty3000 pointed out, you can't easily share test-only code between projects/modules, and we'd like to keep the JUnit 4 & 5 modules separate. When I've done this before it's worked because the concrete subclass test cases were in the same project. One possible workaround is to have a separated project that is an "internal" project, and have the source in src/main/java, and use that as test dependencies. I'm not sure if it's worth it for this one test? If we find other use cases though, it might be worthwhile investigating this.

**Comment by bjhargrave** [comment]
So shall we close this issue for now?
