### ISSUE TITLE
[junit5] Revisit constructor injection 

### ISSUE THREAD

**Issue by kriegfrj** [osgi/osgi-test#463]
At the moment, we have made a conscious decision to not support constructor injection. The reasoning being that it offers nothing over-and-above what injection on `@BeforeAll` and `@BeforeEach` can achieve.

A recent experience with constructor injection in DS 1.4 caused me to rethink this decision. There is a potential reason to prefer constructor injection (where appropriate) - it gives you a mechanism to inject into `final` fields.

**Comment by bjhargrave** [comment]
But I don't think `final` fields are critical for test cases. Tests are not production code and one does not generally have to worry about safe publication of test case objects since the test framework itself (e.g. JUnit) will provide, indirectly, all the necessary memory barriers to make sure the test case object is safely published.

Constructor injection would be "controlled" by TestInstance since that controls the life cycle of the test object.

**Comment by kriegfrj** [comment]
> But I don't think `final` fields are critical for test cases. Tests are not production code and one does not generally have to worry about safe publication of test case objects since the test framework itself (e.g. JUnit) will provide, indirectly, all the necessary memory barriers to make sure the test case object is safely published.
>

Certainly, they are less critical than in production code. However, I can forsee that they might be useful enough that some developers might like to use it. I don't think we should prevent them on purely ideological grounds (so far they are mostly prevented on pragmatic grounds - ie, we haven't implemented it).

I don't think this support would be difficult to add or much of a maintenance burden to keep.
