### ISSUE TITLE
@ServiceSource should give a meaningfull error if no services are found

### ISSUE THREAD

**Issue by laeubi** [osgi/osgi-test#593]
Currently one can use `@ServiceSource` with a `@ParameterizedTest`, but this has the problem that if the service source do not match any service (that is an empty list is returned), JUnit throws a strange eror to the user that is not very helpful:

> org.junit.platform.commons.PreconditionViolationException: Configuration error: You must configure at least one set of arguments for this @ParameterizedTest

Obviously the user has configured something... Thus it seems `@ServiceSource` should give a more meaningful message here.

**Comment by bjhargrave** [comment]
ServiceArgumentsProvider can return an empty stream if the ServiceSource does not match any service or a stream with an empty Arguments if the parameterized test method's parameter types do not match a type supported by the service type (S, ServiceReference<S>, Dictionary<String,Object>, Map<String,Object>).

And given that there could be multiple sources (as you note), it is unclear that it should be illegal to return an empty stream.

However, it should probably be an error (throw exception) if there are services matching the ServiceSource but the parameterized test method's parameter types do not match a type supported by the service type. This is clearly a programming error. That is, ServiceArgumentsProvider should never put an empty Arguments in the stream. But an empty stream is not an error since there can be other sources.

**Comment by laeubi** [comment]
Yes the problem shows up if nothing match, maybe it would be good to have a flag at the anottation (that is enabled by default) that reads `failIfnoneMatch`, then the user can choose if he likes to expect that at least one matches. Probably even similar to what DS does for references having cardinality = `OPTIONAL`, `AT_LAEST_ONE`, `MULTIPLE`, ...
