### ISSUE TITLE
Goal of the Project - Tests inside an running Framework only?

### ISSUE THREAD

**Issue by stbischof** [osgi/osgi-test#65]
The most Test-Cases expects, that they are running inside an running OSGi-Framework, right?
Is that the only goal of this Project?

PR #64 tries to show a way to run the test also as unit-tests using an framework-extension. This takes the existing Framework(integration-test) or launches a new (unit test).

Is it useful to try out more in this way?

**Comment by bjhargrave** [comment]
I am not sure I understand the question. This project is about supporting testing for OSGi code. Primarily this is code in bundles running in an OSGi framework. That is, like OSGi JUnit test in Bndtools, TestOSGi task type in Bnd Gradle plugin, and bnd-testing-maven-plugin.

I am unclear what you are getting at here so I don't know what _your_ goal is with the PR.

I don't think we want to mock an OSGi framework to run tests.

**Comment by stbischof** [comment]
Sorry for the bad explanation and English.
I tried to have something like the bnd launchpad. Where each test could launch a single new Framework.

**Comment by rotty3000** [comment]
My personal goal for this project is to run tests inside an OSGi framework.

**Opinion:** When using component frameworks for the business logic of your application logic (which you _should_ do) you should already be well equipped for unit testing with plain JUnit/TestNG/SomethingElse because your application logic should be able to be pretty much abstracted from OSGi. However, if you are testing aspects which are affected by the dynamics of an OSGi system; like service dependency management, whiteboard readiness, configuration lifecycle and effects on your logic, then I feel you _must_ test in a real framework.

**Comment by stbischof** [comment]
I agree that you have to test it in a real framework. But starting. A new framework each test or test class could prevent side for effects from other test.
Using unit test (each starting a new Framework)  makes it possible to have parallel test.

**Comment by rotty3000** [comment]
so one of the other goals of this project is to handle side effects better :) If you check the BundleContext and Service rules/extensions they try really hard to do exactly that! :)
